export const PERMISSIONS = [
  'dashboard.view',
  'lead.view',
  'lead.create',
  'lead.update',
  'lead.delete',
  'lead.assign',
  'followup.view',
  'followup.create',
  'followup.update',
  'followup.delete',
  'recruitment.view',
  'candidate.create',
  'candidate.update',
  'candidate.delete',
  'candidate.move_stage',
  'finance.view',
  'finance.create',
  'finance.update',
  'finance.delete',
  'finance.approve',
  'file.view',
  'file.upload',
  'file.download',
  'file.delete',
  'user.view',
  'user.create',
  'user.update',
  'user.delete',
  'role.view',
  'role.manage',
  'audit.view',
] as const;
export type Permission = (typeof PERMISSIONS)[number];
